from . import research_area
from . import discipline_type
from . import appointment_form
from . import decision_type
from . import teacher_title
from . import teaching_method
from . import lecturer_status
from . import commendation_method
from . import award_type
from . import object_classification
from . import income_type
from . import major_program
from . import education_level
from . import research_level
from . import topic_research
from . import type_of_training
from . import army_rank
from . import ums_revenue
from . import ums_expense
from . import certificate_type
from . import training_type
from . import ums_specialization
from . import scholarship_type
from . import wounded_soldier_class
from . import education_form
from . import education_type
from . import academic_year
from . import priority_household_type
from . import ums_cohort
from . import research_title
from . import scientific_title
from . import exempt_category
from . import research_proposal
from . import funding_agency
from . import hr_academic
from . import hr_tilte
from . import ums_subject
from . import subject_type
from . import ums_job_title
from . import paygrade_level
from . import ums_salary_grade
from . import ums_type_reward
from . import revenue_source
from . import expense_source
from . import res_district_ward
from . import res_state_district
from . import ums_blood_type
from . import ums_room_type
from . import ums_place
from . import ums_classroom
from . import ums_syllabus
from . import ums_type_operation
from . import ums_officer_evaluate
from . import academic_division
from . import policy_subject_social_benefit
from . import ums_education_regulations
from . import ums_education_background
from . import ums_cost_resources
