# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Ums Master',
    'version': '1.0',
    'author': 'BMSTECH',
    'summary': '',
    'sequence': 1,
    'description': """
    """,
   'depends': [],

   'data': [
       'security/ir.model.access.csv',
     'views/menu.xml',
'views/research_area_views.xml',
'views/discipline_type_views.xml',
'views/appointment_form_views.xml',
'views/decision_type_views.xml',
'views/teacher_title_views.xml',
'views/teaching_method_views.xml',
'views/lecturer_status_views.xml',
'views/commendation_method_views.xml',
'views/award_type_views.xml',
'views/object_classification_views.xml',
'views/income_type_views.xml',
'views/major_program_views.xml',
'views/education_level_views.xml',
'views/research_level_views.xml',
'views/topic_research_views.xml',
'views/type_of_training_views.xml',
'views/army_rank_views.xml',
'views/ums_revenue_views.xml',
'views/ums_expense_views.xml',
'views/certificate_type_views.xml',
'views/training_type_views.xml',
'views/ums_specialization_views.xml',
'views/scholarship_type_views.xml',
'views/wounded_soldier_class_views.xml',
'views/education_form_views.xml',
'views/education_type_views.xml',
'views/academic_year_views.xml',
'views/priority_household_type_views.xml',
'views/ums_cohort_views.xml',
'views/research_title_views.xml',
'views/scientific_title_views.xml',
'views/exempt_category_views.xml',
'views/research_proposal_views.xml',
'views/funding_agency_views.xml',
'views/hr_academic_views.xml',
'views/hr_tilte_views.xml',
'views/ums_subject_views.xml',
'views/subject_type_views.xml',
'views/ums_job_title_views.xml',
'views/paygrade_level_views.xml',
'views/ums_salary_grade_views.xml',
'views/ums_type_reward_views.xml',
'views/revenue_source_views.xml',
'views/expense_source_views.xml',
'views/res_district_ward_views.xml',
'views/res_state_district_views.xml',
'views/ums_blood_type_views.xml',
'views/ums_room_type_views.xml',
'views/ums_place_views.xml',
'views/ums_classroom_views.xml',
'views/ums_syllabus_views.xml',
'views/ums_type_operation_views.xml',
'views/ums_officer_evaluate_views.xml',
'views/academic_division_views.xml',
'views/policy_subject_social_benefit_views.xml',
'views/ums_education_regulations_views.xml',
'views/ums_education_background_views.xml',
'views/ums_cost_resources_views.xml',
   ],
   'demo': [],
   'qweb': [],
   'license': 'LGPL-3',
   'installable': True,
   'application': True,
   'auto_install': False,
}
